"""OpenCTI internal-enrichment connector. The only module that imports pycti.

It reads through the shared lookout_core OpenCTI adapter, using pycti's own authenticated
client as the transport, and writes its result back as a Note."""
import datetime
import os

import yaml
from pycti import OpenCTIConnectorHelper, get_config_variable

from lookout_core import analysis as A
from lookout_core import prompts as P
from lookout_core.ollama import Ollama
from lookout_core.sources.opencti import OpenCTISource


def _bool(v):
    return str(v).strip().lower() in ("1", "true", "yes", "on")


class LookoutConnector:
    def __init__(self):
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config.yml")
        config = yaml.load(open(path), Loader=yaml.FullLoader) if os.path.isfile(path) else {}
        self.helper = OpenCTIConnectorHelper(config)

        def cfg(env, key, default=None, **kw):
            return get_config_variable(env, ["lookout", key], config, default=default, **kw)

        self.model = cfg("LOOKOUT_OLLAMA_MODEL", "ollama_model", required=True)
        self.llm = Ollama(cfg("LOOKOUT_OLLAMA_URL", "ollama_url", "http://host.docker.internal:11434"), self.model,
                          int(cfg("LOOKOUT_OLLAMA_TIMEOUT", "ollama_timeout", 600, isNumber=True)))
        self.num_ctx = int(cfg("LOOKOUT_NUM_CTX", "num_ctx", 12288, isNumber=True))
        self.output = str(cfg("LOOKOUT_OUTPUT", "output", "bulletin")).lower()          # bulletin | summary
        self.question_types = {t.strip() for t in str(cfg("LOOKOUT_QUESTION_TYPES", "question_types", "Case-Rfi")).split(",") if t.strip()}
        self.max_tlp = str(cfg("LOOKOUT_MAX_TLP", "max_tlp", "TLP:RED"))
        self.link_found = _bool(cfg("LOOKOUT_LINK_FOUND_ENTITIES", "link_found_entities", "false"))
        self.label = str(cfg("LOOKOUT_LABEL", "label", "ai-generated") or "").strip()
        if self.output not in ("bulletin", "summary"):
            raise ValueError("LOOKOUT_OUTPUT must be 'bulletin' or 'summary'")
        A.tlp_allowed([], self.max_tlp)           # validates the value at start-up
        # pycti's client supplies the URL, token and TLS settings, so no second credential is needed
        self.source = OpenCTISource({"id": "opencti", "kind": "opencti", "label": "OpenCTI"}, transport=self.helper.api.query)
        self.prompts = P.build(self.source.info())

    def _log(self, msg):
        lg = getattr(self.helper, "connector_logger", None)
        (lg.info if lg else self.helper.log_info)(msg)

    def _label_ids(self):
        if not self.label:
            return []
        try:
            lab = self.helper.api.label.read_or_create_unchecked(value=self.label, color="#2F5BFF")
            return [lab["id"]] if lab else []
        except Exception as e:                     # labels are a nicety; never fail the job over them
            self._log(f"Could not create label '{self.label}': {e}")
            return []

    def _create_note(self, abstract, body, object_ids, marking_ids):
        today = datetime.date.today().isoformat()
        content = (f"{body}\n\n---\n*Generated by {self.model} through the Lookout connector on {today}. "
                   "AI-generated from OpenCTI records and not independently verified. Review before use.*")
        kwargs = dict(abstract=A.clip(abstract, 120), content=content, objects=object_ids, objectMarking=marking_ids)
        labels = self._label_ids()
        try:
            return self.helper.api.note.create(**kwargs, **({"objectLabel": labels} if labels else {}))
        except Exception:
            if not labels:
                raise
            return self.helper.api.note.create(**kwargs)          # retry without the label

    def _process_message(self, data):
        entity_id = data["entity_id"]
        entity_type, markings = self.source.markings(entity_id)
        if not A.tlp_allowed(markings, self.max_tlp):
            raise ValueError(f"Entity marking exceeds LOOKOUT_MAX_TLP ({self.max_tlp}); nothing was sent to the model.")
        marking_ids = [m["id"] for m in markings]
        if entity_type in self.question_types:
            return self._answer_question(data, entity_id, marking_ids)
        return self._write_entity_note(entity_id, marking_ids)

    def _write_entity_note(self, entity_id, marking_ids):
        rec = self.source.get(entity_id)
        if not rec:
            raise LookupError(f"Entity {entity_id} was not found or is not readable by the connector.")
        payload = A.entity_payload(rec, self.source.related(entity_id), datetime.date.today().isoformat())
        if self.output == "bulletin":
            system, user, kind = self.prompts["bulletin"], "Write the bulletin from this data (JSON):\n", "bulletin"
        else:
            system, user, kind = self.prompts["entity"], "Analyse this record (JSON):\n", "summary"
        self._log(f"Generating {kind} for {rec['name']}")
        text = self.llm.chat([{"role": "system", "content": system}, {"role": "user", "content": user + A.dumps(payload)}], num_ctx=self.num_ctx)
        if not text.strip():
            raise ValueError("The model returned an empty answer.")
        self._create_note(f"Lookout {kind}: {rec['name']}", A.tidy(text), [entity_id], marking_ids)
        return f"Created a {kind} note on {rec['name']} using {self.model}."

    def _answer_question(self, data, entity_id, marking_ids):
        stix = data.get("stix_entity") or {}
        question = "\n".join(x for x in [stix.get("name"), stix.get("description")] if x).strip()
        if not question:
            raise ValueError("The request has no title or description to read as a question.")
        ctx = A.build_context(question, self.source, self.llm, self.prompts["plan"])
        if ctx["groups"]:
            user = f'The analyst asked: "{question}"\n\nWhat OpenCTI returned (JSON):\n{A.dumps(A.context_payload(ctx))}'
            text = self.llm.chat([{"role": "system", "content": self.prompts["question"]}, {"role": "user", "content": user}], num_ctx=self.num_ctx)
            body = A.tidy(text) + "\n\n" + A.understood_markdown(ctx)
        else:
            body = "## Answer\nOpenCTI has no records for the entities that could be picked out of this question.\n\n" + A.understood_markdown(ctx)
        objects = [entity_id] + ([r["id"] for g in ctx["groups"] for r in g["records"]] if self.link_found else [])
        self._create_note(f"Lookout answer: {question.splitlines()[0]}", body, objects, marking_ids)
        return f"Answered the question using {len(ctx['groups'])} matched entities."

    def start(self):
        self.helper.listen(self._process_message)
